#!/usr/bin/python3
def raise_exception_msg(message=""):
    """
    Raises a NameError exception with a message
    
    Args:
        message: The message to include in the exception
    """
    raise NameError(message)
